package day19.ExceptionHandling;

public class ExceptionHandlin14 {
	public int divideNum(int m,int n) throws ArithmeticException{
		int div=m/n;
		return div;
	}
	public static void main(String args[]) {
		ExceptionHandlin14 e=new ExceptionHandlin14 ();
		 	try {
		 		System.out.println(obj.divideNum(25,9));
		 	}
	}

}
